Feature/cnv 84 header kaneko
Conovel/frontend pull request #10
Opened 2024-10-06 15:25 UTC by Yuya757

## JIRAチケットURL
https://techno-kuro-novel.atlassian.net/browse/CNV-84

---
## 実装内容
ヘッダーおよびサイドバーのデザインを行った（作業途中）
### 機能要件

このセクションでは、以下URL参照先（機能要件）の記載を引用し、どの要件を満たすための実装をしたのかを記載します。
https://techno-kuro-novel.atlassian.net/wiki/spaces/Conovel/pages/3145744
なお、上記URLに含まれない実装をしている場合は、適宜参照先URLを付して、記載を引用して記載してください。
必ず製造タスクの根拠を示してください。

MIROデザイン：
![image](https://github.com/user-attachments/assets/0cf48dcb-4f23-4439-a6dc-c7884529e47d)

その他資料：
svgファイルのインポート時の型エラー解消など
https://qiita.com/Kairi_Yasunnde/items/dd4eeb52d140cd309da5

- 機能要件1
　共通要素：ヘッダー
- 機能要件2
- 機能要件3

また、上記要件資料を参照し、漏れがないことを確認したら、チェックします。

[☑] 一部懸念あり；ヘッダーのメニュー・ロゴ・アイコンの位置調整がうまくいかない

### 非機能要件

このセクションでは、以下URL参照先（非機能要件）の記載を引用し、どの要件を満たすための実装をしたのかを記載します。
https://techno-kuro-novel.atlassian.net/wiki/spaces/Conovel/pages/1376286/_PJ
なお、上記URLに含まれない実装をしている場合は、適宜参照先URLを付して、記載を引用して記載してください。

[☑] 特になし

---

## 自身で確認した動作のエビデンス（スクショ等）

|![image](https://github.com/user-attachments/assets/ef5c6b80-375c-46cc-b232-078dea70a8d7)|
![image](https://github.com/user-attachments/assets/99c97115-065c-4e6b-9f15-7f21ebb107ed)|

### 動作確認エビデンス1
左上ボタンクリックでサイドバーの開閉を確認

### 動作確認エビデンス2

---

## 結合テスト・受入テストに持ち越すテスト項目（必ず1つ以上作成）
本PullReqで洗い出し記載して、Mergeしたら、以下に整理転記する
https://techno-kuro-novel.atlassian.net/wiki/spaces/Conovel/pages/38567991

### テスト要求1
サイドバー開閉が起こるか
### テスト要求2
ヘッダーが（スマホ画面の範囲で）レスポンシブに動くか
### テスト要求3

2024-10-06 21:29 UTC, technokuro reviewed
初見軽くコメント

2024-10-06 21:29 UTC, technokuro commented on src/components/header/index.tsx
> +                <IconButton onClick={handleOpenUserMenu} sx={{ p: 0 }}>
アイコンコンポーネント　としてコンポーネント化する想定ですね
WIP状態だと思いました

2024-10-06 21:29 UTC, technokuro commented on src/components/header/index.tsx
> +  const pages = ['Profile', 'Account', 'Dashboard', 'Logout']; // ここで直接定義
表記ゆれしそうなので、定数化したいですね

2024-10-07 12:21 UTC, azufb requested changes
@Yuya757 
コメントしてます！  
ご確認とご対応、よろしくお願いいたします！

2024-10-07 12:21 UTC, azufb commented on src/components/header/index.tsx
> +            {' '}
@Yuya757 
これは無くて良いような？  
フォーマット都合のような気がするので、空行無くしたら、` {' '}`入らなくなるかなと思いました！

2024-10-07 12:21 UTC, azufb commented on src/components/header/index.tsx
> +                src='../image/conovel_header_logo.webp'
@Yuya757 
同じ画像を指定しているかと思うので、下のBoxと同じく、`logo`を使えるかなと思いました！

2024-10-07 12:21 UTC, azufb commented on src/components/header/index.tsx
> +  const [anchorElUser, setAnchorElUser] = useState<HTMLElement | null>(null);
@Yuya757  
Muiのサンプルを参考にして実装されたのかなと思うのですが、変数名については、もう少しわかりやすいものを使って頂けると助かります！  
パッと見で伝わりにくいかもと思ってしまいました..💦

2024-10-07 12:21 UTC, azufb commented on src/components/header/index.tsx
> +                pages={['Home', 'Account', 'Administer', 'Policy', 'logout']}
@Yuya757   
JSXの中でべた書きで配列宣言すると可読性が落ちてしまうので、くろさんがコメントされている定数化等の対応できましたら、その定数を渡すようにして頂けると！

2024-10-07 12:21 UTC, azufb commented on src/components/sidebar/index.tsx
> +  pages: ('Home' | 'Account' | 'Administer' | 'Policy' | 'logout')[];
@Yuya757   
ここに文字列リテラルで指定するのであれば、別のところで宣言しておいた方が見やすいかなと思いました！

2024-10-07 12:21 UTC, azufb commented on src/components/sidebar/index.tsx
> +          (event as React.KeyboardEvent).key === 'Shift')
@Yuya757 
キーボード操作の対応、ありがとうございます！！
良いと思います！！👍👍👍

LGTM！

2024-10-07 12:21 UTC, azufb commented on src/components/sidebar/index.tsx
> +
@Yuya757   
こちらは、コンポーネントに切り分けちゃって良いかと思いました！  
`src/components`配下に入れるというより、このファイル内で別途定義するくらいで良いかなと思います。

2024-10-07 12:27 UTC, azufb commented
@Yuya757 
コードレビューとはまた別になるのですが、PRのタイトルは何の実装をしたPRなのか、わかりやすくして頂けると、助かります！！

例えば、`Feature/cnv 84 header kaneko`ではなく、`ヘッダーUI実装`とかですね。

2024-10-07 16:00 UTC, technokuro commented
@azufb @Yuya757 
PR　のマージ先って、 `develop` でいいんでしたっけ？
エピックでブランチ切ります？

`develop`
　┗ `CNV-78_header_sidebar`
　　　┗ `CNV-84_header`
とか？

2024-10-08 23:49 UTC, ryo-i commented
@Yuya757 
cc @azufb @technokuro 
まだローカル環境での表示や動作の確認ができていないのですが、貼っていただいたスクリーンショット画像を見て感じたことを書きます。

アイコンの中に機能が直感的に感じられないものがありそうなので、アイコンの下に数文字の小さい文字でボタンの意味を表す単語を入れるのはいかがでしょうか。

参考：
![スクリーンショット 2024-10-09 8 47 15](https://github.com/user-attachments/assets/1e0b0c54-15d0-4fd9-83de-8f384a1b4699)
Youtube、X（元Twitter）、GitHubなどいくつかのSPアプリのメニューをボタンを見てみたところ、アイコン+文字の形式でした

2024-10-09 13:09 UTC, azufb commented
@technokuro @Yuya757 @ryo-i 

> PR　のマージ先って、 develop でいいんでしたっけ？
> エピックでブランチ切ります？

一応、以前こんな感じで話はしてました！
https://techno-kuro-novel.atlassian.net/browse/CNV-108?focusedCommentId=10268

ただ、今回はサブタスク（子課題）を作らずにやって頂いているみたいなので、今回は、このままで良いかなと思ってます。  
エピックでチケットを切る必要はないかなと思ってます。タスクでブランチ切って、そこからサブタスクのブランチを切る感じですね。

2024-10-12 09:24 UTC, merged

2025-02-16 05:58 UTC, Yuya757 commented
2025/02/16時点でのスクリーンショット
![image](https://github.com/user-attachments/assets/c5fdc372-1c48-4dcc-9682-82a89bb3a18f)