小説一覧リスト，コンポーネントの作成
Conovel/frontend pull request #17
Opened 2024-10-13 10:47 UTC by Yuya757

## JIRAチケットURL
https://techno-kuro-novel.atlassian.net/browse/CNV-87

---
## 実装内容

### 機能要件

このセクションでは、以下URL参照先（機能要件）の記載を引用し、どの要件を満たすための実装をしたのかを記載します。
https://techno-kuro-novel.atlassian.net/wiki/spaces/Conovel/pages/3145744
なお、上記URLに含まれない実装をしている場合は、適宜参照先URLを付して、記載を引用して記載してください。
必ず製造タスクの根拠を示してください。

　例　テーブル定義Miroやその他資料

- 機能要件1
  miroに挙げた図は以下の通り．
![スクリーンショット 2024-10-13 125653](https://github.com/user-attachments/assets/6a82540c-99c6-4e15-a7b6-153f11876467)

また、上記要件資料を参照し、漏れがないことを確認したら、チェックします。

[☑] 要件漏れがないことを確認済み
[] 一部懸念あり

### 非機能要件

特になし

---

## 自身で確認した動作のエビデンス（スクショ等）

### 動作確認エビデンス1
例　未読通知を複数ページに渡って閲覧して、既読になる様子
![image](https://github.com/user-attachments/assets/e6d7ea1c-b629-4207-9296-ed66938d0906)

### 動作確認エビデンス2

---

## 結合テスト・受入テストに持ち越すテスト項目（必ず1つ以上作成）
本PullReqで洗い出し記載して、Mergeしたら、以下に整理転記する
https://techno-kuro-novel.atlassian.net/wiki/spaces/Conovel/pages/38567991

### テスト要求1
各項目が問題なく表示されているか
### テスト要求2

### テスト要求3

2024-10-13 10:50 UTC, Yuya757 commented
縦横比が思って言えたよりも横長で収まってしまった．
1行目・題名は長くなって複数行になる可能性がある？
ならばスペースを確保した方が良いかなど少しご相談したいです！

2024-10-13 13:25 UTC, azufb requested changes
@Yuya757   
レビューコメントしてます！
一覧の部分はもうちょっとしっかり見たいところではあるのですが、今回、ディレクトリについてコメントしているので、まずそちらを対応して頂いてから、細かいところは見ようと思います！

また、今はモックで対応して頂いているかと思いますが、一覧なので、最終的には配列で受け取ることになるので、モックデータについても配列を想定して実装して頂けると良いかなと思ってます。（その方が後々楽かなと思います！）

2024-10-13 13:25 UTC, azufb commented on src/components/novel_list/index.tsx
@Yuya757 
こちら、小説一覧の実装であれば、共通で使うコンポーネント`src/components`ではなく、`src/features/NovelList`で実装するので良いかなと思いました！
ただ、一覧の中の各小説のカード部分の実装については、この`src/components`にあって良いと思います！
カード部分の実装だけにするのであれば、ディレクトリ名も`novel_list`ではなく、`card`実装であることがわかるようなディレクトリ名にした方が良いですね！

2024-10-13 13:25 UTC, azufb commented on src/components/tags/index.tsx
> +}
@Yuya757   
1つTagコンポーネントを作って、`label`とかの可変の内容を`props`で受け取るようにするので良いかなと感じました！！

2024-10-13 13:34 UTC, azufb commented
@Yuya757   
> 1行目・題名は長くなって複数行になる可能性がある？

最近では、長い題名のものも増えているので、複数行になる可能性はありますね！
今回新規作成は実装なしですが、題名は`最長 128 文字`までの想定で要件検討しておりました！！
https://techno-kuro-novel.atlassian.net/wiki/spaces/Conovel/pages/3145744#4.-%E6%96%B0%E8%A6%8F%E4%BD%9C%E6%88%90%E6%A9%9F%E8%83%BD

@technokuro @ryo-i @Yuya757 
タイトルが複数行になった場合、どういうデザインがベターでしょう...？
私は、もし何行にもわたるのであれば、2行目まで表示などにして、それ以降は3点リーダで省略とかの対応があった方が見やすいのかなと考えております！
（タイトル最大128文字全て表示となると見にくそうかなというのと、デザインのバランスが崩れそう...）

ただ、省略することによる懸念点としては、タイトルが全部見えなくなってしまうので、読む小説を「タイトルから選ぶ」ことができなくなってしまうのかな？というところですね...。

2024-10-13 23:29 UTC, ryo-i commented
@azufb @Yuya757 cc @technokuro 
長いタイトルの小説の表示について、他のサイトの例も調べて見ました。
下記のパターンが多いようです。
- 一覧画面：2行で3点リーダー
- 単一画面：全表示
https://techno-kuro-novel.atlassian.net/browse/CNV-87?focusedCommentId=10329
----
また、PC画面で見た時に横幅が広いのが気になりました。
PCやタブレットのメディアクエリでmin-widthを設定すると良さそうに思います。

SP
![スクリーンショット 2024-10-14 8 06 42](https://github.com/user-attachments/assets/cbf8b399-baab-4dbf-b99a-a0cf0f07a67b)

PC
![スクリーンショット 2024-10-14 8 06 50](https://github.com/user-attachments/assets/bf38a2b5-07d6-46fa-b485-e64913a7bc98)

2024-10-14 00:27 UTC, technokuro commented
2行3点リーダーでいいと思いますよ 👍

2024-10-14 02:33 UTC, azufb commented
@ryo-i @technokuro 

> 長いタイトルの小説の表示について、他のサイトの例も調べて見ました。
> 下記のパターンが多いようです。
> 
> 一覧画面：2行で3点リーダー
> 単一画面：全表示
> 参考：https://techno-kuro-novel.atlassian.net/browse/CNV-87?focusedCommentId=10329

> 2行3点リーダーでいいと思いますよ 👍

ありがとうございます！！

@Yuya757 
では、長い題名を考慮して、2行まで表示・それ以降は3点リーダ表示でお願いいたします！  
1行目については、1行表示でそれ以降は3点リーダで良いかなと思います！！

また、つっちーさんからカードの幅についてレビューコメント頂いているようなので、ご確認お願いいたします！！

2024-10-21 13:32 UTC, azufb commented
@Yuya757   
SPメインですので、PCでのカードの幅の調整については、こちらのPRではなく、リファクタチケットとして別途対応でOKです！
チケット切っておきます。

2024-10-21 15:13 UTC, Yuya757 commented
@azufb @ryo-i @technokuro 皆様，レビューありがとうございます．
少し時間がかかってしまいましたが，だいぶそれっぽいものができてきました．
再レビューお願いいたします．
![image](https://github.com/user-attachments/assets/5e0e47b3-66f2-487b-b102-71187863aec1)

2024-10-22 12:43 UTC, azufb requested changes
@Yuya757   
レビューコメントしてます！
また、`Container/Presentational`パターンを使って頂けるとロジックと描画でコンポーネントを分けることができるので見通しがより良いかなと思いますので、検討頂けると嬉しいです！！

2024-10-22 12:43 UTC, azufb commented on src/components/tags/index.tsx
> +}
@Yuya757   
こういう実装を`tags`でしておくと、各小説がコンポーネントを持たず、ラベルを渡すだけで済みそうです！！

```
interface TagProps {
  label: string;
}

export const Tag = ({ label }: TagProps) => {
  return (
    <Chip
      label={label}
      size='small'
      sx={{ borderRadius: '4px', border: '1px solid black' }}
      variant='outlined'
    />
  );
};
```

2024-10-23 11:36 UTC, Yuya757 commented on src/components/tags/index.tsx
> +}
ありがとうございます．種類が決まっているものなのですべてコンポーネント化しないといけないという頭でした．propsでstring渡してしまえば解決ですね！

2024-10-23 11:40 UTC, Yuya757 commented
ありがとうございます．設計の段階でcontainer/presentationだったことをすっかり忘れていました．すっきりと修正しすくなったと思います！
![image](https://github.com/user-attachments/assets/815a6816-c304-4cda-b68d-ea73c2f707b6)

2024-10-23 13:59 UTC, azufb approved these changes
@Yuya757 
approveです！

2024-10-23 14:00 UTC, merged