小説閲覧画面のデザインを行った
Conovel/frontend pull request #20
Opened 2024-10-20 15:22 UTC by Yuya757

## JIRAチケットURL
https://techno-kuro-novel.atlassian.net/browse/CNV-89

---
## 実装内容
小説閲覧画面のデザイン実装を行った．
### 機能要件

このセクションでは、以下URL参照先（機能要件）の記載を引用し、どの要件を満たすための実装をしたのかを記載します。
https://techno-kuro-novel.atlassian.net/wiki/spaces/Conovel/pages/3145744
なお、上記URLに含まれない実装をしている場合は、適宜参照先URLを付して、記載を引用して記載してください。
必ず製造タスクの根拠を示してください。

　例　テーブル定義Miroやその他資料

- 機能要件1
![image](https://github.com/user-attachments/assets/91a1a318-6b43-439c-a45a-5e91cdc98c2c)

- 機能要件2
- 機能要件3

また、上記要件資料を参照し、漏れがないことを確認したら、チェックします。

[] 要件漏れがないことを確認済み
[☑] 一部懸念あり：wip状態．デザイン・構成についてアドバイスいただけるとありがたいです．またmainPanelを縦線が貫通してしまっており，zIndexを色々いじりましたが解決できておりません．

### 非機能要件

特になし

---

## 自身で確認した動作のエビデンス（スクショ等）
![image](https://github.com/user-attachments/assets/7909658c-7805-4b07-a4c4-1556217b4059)

### 動作確認エビデンス1
例　未読通知を複数ページに渡って閲覧して、既読になる様子

### 動作確認エビデンス2

---

## 結合テスト・受入テストに持ち越すテスト項目（必ず1つ以上作成）
本PullReqで洗い出し記載して、Mergeしたら、以下に整理転記する
https://techno-kuro-novel.atlassian.net/wiki/spaces/Conovel/pages/38567991

### テスト要求1
ボタンクリックで画面遷移が起こるか
### テスト要求2

### テスト要求3

2024-10-22 12:26 UTC, azufb requested changes
@Yuya757 
いくつかレビューコメントいたしました！  
また、今ダミーデータを入れて頂いていますが、配列で受け取る想定では対応されていないかと思うので、今後APIつなぎこんだ時にまた修正が入ってしまうかなと想定しております💦
可能であれば、配列で受け取る想定の実装をしておくと、後々楽かな～と感じました！

2024-10-22 12:26 UTC, azufb commented on src/features/NovelView/index.tsx
> +      </div>
@Yuya757   
mainのコンポーネントの背景色を指定したら、線が隠れるのでは？と思いました！  
見たところ、背景色の指定がなかったので、`transparent`になってしまって、後ろにある線が見えているのかもと思いました。

2024-10-22 12:26 UTC, azufb commented on src/features/NovelView/index.tsx
> +            </div>
@Yuya757   
カードの一部だけ背景色が付いているのは少し違和感ありますね...！  
「続きを自分で書く」の全体に背景色を付けて、「＋」マークの背景色を青っぽい色にするなどしたら、不自然ではなくなるかなという気がしました！！

2024-10-22 12:26 UTC, azufb commented on src/features/NovelView/index.tsx
@Yuya757   
``Container/Presentational``パターンを使って頂けたら...と思っております！  
そうなると、以下の変更が必要になります。
- ファイル名
  - `NovelViewPresenter.tsx`
- コンポーネント名
  - `NovelViewPresenter`

2024-10-22 12:26 UTC, azufb commented on src/features/NovelView/index.tsx
> +        </div>
@Yuya757 
同じようなレイアウトがいくつか並ぶと思うので、このファイル内で良いので、別途コンポーネントに切り出しても良いかもしれないです！！

2024-11-02 13:05 UTC, technokuro commented on src/features/NovelView/NovelViewContainer.tsx
> +const posts = [
@Yuya757 
`//TODO デモデータ` とか、あとで消すことを明示しましょう
また、まもなく openapi にて、型が決まります。

https://github.com/Conovel/environment/pull/8/files#diff-ddafcef809286cf061da15b0021fc990bdce577433d759d468773b4abf213906R276-R309
👆ここの型を意識してデモデータを作り直しましょう
サーバからはこの形で供給されるわけです

本件同様のコメントを　※　と表記します。

2024-11-02 13:05 UTC, technokuro commented on src/features/NovelView/NovelViewPresentation.tsx
> +interface Post {
※

2024-11-02 13:05 UTC, technokuro commented on src/features/NovelView/NovelViewPresentation.tsx
> +interface NovelViewPresentationProps {
※　名称合わせよろしくです！

サーバからは以下の名称で提供される見込みです
https://github.com/Conovel/environment/pull/8/files#diff-ddafcef809286cf061da15b0021fc990bdce577433d759d468773b4abf213906L69-R324

2024-11-02 13:05 UTC, technokuro commented on src/features/NovelView/NovelViewPresentation.tsx
> +          <div key={panel.id} style={styles.mainPanel}>
@Yuya757 
Sentence を表現するものですから、コンポーネント化することを視野に

2024-11-02 13:05 UTC, technokuro commented on src/features/NovelView/NovelViewPresentation.tsx
> +          <div key={post.id}>
@Yuya757 
下部のものとほぼ同等ですね。
コンポーネント化を視野に

2024-11-02 13:05 UTC, technokuro commented on src/features/NovelView/styles.tsx
> +export const styles: { [key: string]: React.CSSProperties } = {
@Yuya757 @azufb @ryo-i 
ここは @azufb @ryo-i の意見もぜひ！
私の経験ですと、
- とあるコンポーネントでのみ使う style は そのコンポーネント tsx の中だけで定義する
- 複数の箇所で使う style はここのように共通定義する
という体験でした。

どちらでもいいです（後学のため）

2024-11-02 13:50 UTC, azufb commented on src/features/NovelView/styles.tsx
> +export const styles: { [key: string]: React.CSSProperties } = {
@technokuro @Yuya757 @ryo-i 
うーん、自分の経験では、これは使うスタイリングライブラリにもよる...という感じがします💦

- `styled-components`を使うようなPJでは...
  - このPRの`src/features/NovelView/styles.tsx`でやって頂いているように、スタイル用のファイルに定義しているところはあります。
- ライブラリ側が提供しているコンポーネント（`Box`とか）を使うようなPJでは...
  - そのコンポーネントにpropsとしてスタイルを渡します。

私が今いる現場は、`Chakra UI`というライブラリを使っていて、`Box`など提供されているコンポーネントを使って実装しています。スタイリングは、コンポーネントにpropsとして`width`など渡します。

一応、10/24の定例会で、`div`とかではなく、MUIから提供されているコンポーネントを使いましょうか！という話になった認識をしており、propsをスタイルとして渡すので良いんじゃないかなーという気もしています。  
（定例で、divのことメインで言ってしまったので、良くなかったかもしれないです...。ごめんなさい🙇‍♀️）

ただ、propsとしてつらつらスタイルの定義が渡されるのが、「正直気持ち悪い！」っていう方もいるかとは思うので、好みかなぁーという気もします🙇‍♀️

2024-11-02 23:26 UTC, ryo-i commented on src/features/NovelView/styles.tsx
> +export const styles: { [key: string]: React.CSSProperties } = {
@technokuro @azufb @Yuya757 
確認しました。htmlタグのstyle属性に直接スタイルを設定する方法だとちょっとスタイルのボリュームが肥大化している印象がありますね（添付ファイル参照）
![スクリーンショット 2024-11-03 7 52 52](https://github.com/user-attachments/assets/00067ec5-c06b-4045-b0aa-2a589129cde3)

自分の経験ではプロジェクトによって違いますが
- CSSフレームワーク（tailwindなど）：フレームワークのclassを付ける（なるべくコンポーネントの大元のファイルに）
- CSS in JS（styled-componentsなど）：該当するtsxファイルの中に書く（ハッシュ付きclassが生成されてスコープが閉じられている）
- CSS Modules：該当するtsxと同じコンポーネント内にscssファイルなどを書いてtsxファイルでimportする（同じくハッシュ付きclassが生成されてスコープが閉じられている）
- BEMなど：tsxファイル群とは別の場所でBEMなどの命名規則のscssファイルが作り、そのclassをつける
- style属性に直接スタイル設定：アニメーションで高さや透明度を動的に変えるなどでこの方法をとっている印象があります

※MUIのカスタマイズ方法を調べたところ、tsxファイルの中でstyled 関数を使ってスタイル付きコンポーネントを作成する方法も出てきました（この方法もハッシュ付きのclassが生成されるようです）
https://mui.com/material-ui/customization/how-to-customize/#2-reusable-component

2024-11-06 11:44 UTC, azufb commented on src/features/NovelView/styles.tsx
> +export const styles: { [key: string]: React.CSSProperties } = {
@technokuro @Yuya757 @ryo-i 
皆さん色々経験を回答して頂いてますが、それっきりになってしまっているので、以下に整理しておきます！
「例」と記載しているのは、代表的なライブラリやFWです。
（BEMはどちらかと言うと設計手法寄りのお話かなと思うので、一旦置いとかせて頂きます🙇‍♀️）

そのプロジェクトで使用しているライブラリ・FW、あと個人の好みにもよりますねぇ...😭😭😭

今回Material UIを使っているので、そこも考慮に入れて検討すべきなのかなと個人的には考えています。

--------

### UIライブラリを使う（このプロジェクトはこれ）
2パターンある。プロジェクト や人によります。
- コンポーネントに直接propsとして渡すやり方
- UIライブラリから提供されている`sx`などのpropsに入れて渡すやり方
  - 既にマージ済みのHeaderコンポーネントとかで使って頂いている

例）Material UI、Chakra UI、React-Bootstrap

※Semantic UIなんかは若干違う感じ。

### CSSフレームワークを使う
- フレームワークが提供するclassNameを付ける
（クラスを付けるだけでスタイルの指定ができる）

例）Tailwind CSS

### CSS in JSを使う
2パターンある。プロジェクトによります。
1. tsxファイルの中で一緒に定義するやり方
2. 別途ファイルを用意して定義するやり方（styled-components）

例）styled-components、Emotion、vanilla-extract

### そのほか
- CSS Modules
  - 別途ファイルを用意して定義
- JSXの要素に対し、style属性を渡して直接スタイル指定
  - 他の手段で実現できなかった場合など
- そのコンポーネントの中だけで使うstyleはtsxファイルの中で定義し、複数のコンポーネントで使うstyleはファイルを別途用意して共通で使えるようにする

2024-11-06 21:16 UTC, ryo-i commented on src/features/NovelView/styles.tsx
> +export const styles: { [key: string]: React.CSSProperties } = {
@azufb @technokuro @Yuya757 
> UIライブラリを使う（このプロジェクトはこれ）

個人的にはMUIをあらかじめインストールいるプロジェクトなのでMUIが用意しているコンポーネントを使う（まずはそこからUIを探す）方法でいいような気はしますね。

カスタマイズするは次の手段で、その方法もあずにゃんさんの書かれていたMUIのsxの方法でいいように思いました。
https://github.com/Conovel/frontend/blob/develop/src/components/header/index.tsx

2024-11-06 23:23 UTC, technokuro commented on src/features/NovelView/styles.tsx
> +export const styles: { [key: string]: React.CSSProperties } = {
@azufb @ryo-i @Yuya757 
コード量は少ない方がいい＝UIライブラリのデフォルトに沿う　ということと思います
このPJ内で統一されれば、いずれでも構いません。

MUIを利用することを優先に、Styleのコード量を極力少なくしていきましょうか。

2024-11-06 23:49 UTC, azufb commented on src/features/NovelView/styles.tsx
> +export const styles: { [key: string]: React.CSSProperties } = {
@Yuya757 
Headerコンポーネント等他のコンポーネント同様、Box等のMUIコンポーネントを使って実装するように、修正お願いいたします🙇‍♀

また、他のコンポーネントとスタイルの当て方を合わせて頂けると！！

2024-11-07 01:11 UTC, Yuya757 commented on src/features/NovelView/styles.tsx
> +export const styles: { [key: string]: React.CSSProperties } = {
@azufb @technokuro @ryo-i 皆様，ありがとうございます．順次対応します．

2024-11-13 13:02 UTC, Yuya757 commented
@azufb cc.@technokuro 画面の途中経過です．今後やること：
[画面部分]
- 「続きを自分で書く」ボタンが固定されてしまっているため，スライダーで流せるようにする
- 各テキストカードのアイコンボタンカウントが共通になっているため改善が必要．
[データ周り]
- まだ引数名がバックエンドと共通化できていないためその部分のアップデート
- 通信が発生する部分が個人的にわかり切っていないので，一度ユースケース図など書く．

![image](https://github.com/user-attachments/assets/e37c861c-74dc-40f5-8db5-dd4d8d5e7f97)

2024-11-14 12:30 UTC, azufb commented
- 親の横スクロール無くす
  - 親は直接メインにつながる親のみ表示
- メインで横スクロールできるように
- 「続きを自分で書く」ボタンをfixedとかで浮かせてchildrenは3つ表示
- アイコンボタン押下でバックエンドとAPI通信
  - 評価など

2024-11-16 01:27 UTC, Yuya757 commented
機能の配置はいったん以下のようにしました．
画面幅の比はあとでもう少し考えることとします．
![image](https://github.com/user-attachments/assets/64cff133-5174-4af0-a851-025a6eeff0c3)

2024-11-16 02:02 UTC, ryo-i commented
@Yuya757 
> 機能の配置はいったん以下のようにしました．

中央のmain投稿の左右にもchildrenと同様に前へ、次へのボタンがある想定でをしています。

@azufb @technokuro 
API側は、親投稿（parent）のパラレル（parent_parallel）は廃止して、代わりにmainに対するパラレル（parallel）を追加するつもりでしたが、考えてみたら画面としてら前へ、次へボタンに投稿idを仕込むだけだから、複数件の配列にする必要は無いかもですかね？

- バック側でmainのパラレル投稿の中なら一つ前、一つ後の投稿idを取得して、それの二つのidをレスポストで返す？
- フロント側でparallelの配列の中から一つ前、一つ後ろの投稿idを拾って次へ、前へボタンに仕込む

どっちの方がいいと思いますか？

2024-11-22 12:09 UTC, azufb requested changes
@Yuya757   
レビューコメントいくつかしてます！！
ディレクトリの移動などコメントさせて頂いているので、一回ここで止めます...🙇‍♀️
ご確認とご対応のほど、よろしくお願いいたします！！

2024-11-22 12:09 UTC, azufb commented on src/features/NovelView/NovelViewPresentation.tsx
> +  const [nextPlanCountNext, setNextPlanCountNext] = React.useState<number>(0);
@Yuya757 
`setState`などはどちらかと言えばロジックに分類されるかなと思います！なので、`Presentation`より`Container`の方が適しているかもです！
また、実際には、Reactから使うより、`useState`自体をimportしてきて使うことの方が多い気がします！  
```typescript
// import React from 'react';
import { useState } from 'react';
```

2024-11-22 12:09 UTC, azufb commented on src/features/NovelView/NovelViewPresentation.tsx
> +        />
@Yuya757 
それぞれなんのコンポーネントなのか、区切りがわかるように、コメント入れるとわかりやすいなと思いました！

``` jsx
{/** 親の投稿 */}
<ParentPanel
    ...省略
/>

{/** メイン */}
<MainPanel
    ...省略
/>

{/** 子投稿(後続) */}
<ChildrenPanel
    ...省略
/>
```

2024-11-22 12:09 UTC, azufb commented on src/components/novelview/ChildrenPanel.tsx
@Yuya757 
`novelView（ChildrenPanel・MainPanel・ParentPanel）`を用意するなら、`components`ディレクトリよりも、`features/NovelView`ディレクトリの中でディレクトリを切る方が合っている感じがします。
`components`ディレクトリに作るのは、いくつかのページで共通して使えるコンポーネントですが、`novelView`に関しては投稿閲覧画面特有のスタイル(Children がflexで配置、左右矢印ボタンetc…)を持ってしまっているので、その画面に特化した実装をしている`features`の方に定義されている方が適切なのかなと感じます！！

2024-11-22 12:09 UTC, azufb commented on src/features/NovelView/NovelViewContainer.tsx
> +      posts={[]}
@Yuya757 
この`posts`という配列の`props`はどういう使い方をする想定ですか？  
`mainPanels`や`parentPanel`、`childrenPanel`はそれぞれ`MainPanel`コンポーネント等のそれぞれのコンポーネントに渡すのかなと想像できるのですが、こちらの`posts`だけよくわからず...！！

2024-11-22 12:09 UTC, azufb commented on src/features/NovelView/NovelViewPresentation.tsx
> +  childrenPanel: Panel;
@Yuya757   
折角モックデータ用意して頂いているので、これらを使った実装にしてみてほしいです！！
（具体的には、`ParentPanel`コンポーネントに`parentPanel`を渡して実装するとか...）
これらの`props`をどう使うのか、想定されている実装を見たいです！

2024-11-22 12:16 UTC, azufb requested changes

2024-11-22 12:16 UTC, azufb commented on src/components/novelview/MainPanel.tsx
@Yuya757 
`ChildrenPanel`と同様です！！
https://github.com/Conovel/frontend/pull/20#discussion_r1853780206

2024-11-22 12:16 UTC, azufb commented on src/components/novelview/ParentPanel.tsx
@Yuya757 
`ChildrenPanel`と同様です！！
https://github.com/Conovel/frontend/pull/20#discussion_r1853780206

2024-11-23 13:50 UTC, azufb commented on src/components/novelview/ChildrenPanel.tsx
ちなみに、`novelView`を`features`に入れる場合は、今回は一旦`Container/Presentation`に分けなくて大丈夫です！！

2024-11-28 01:49 UTC, Yuya757 commented on src/features/NovelView/NovelViewContainer.tsx
> +      posts={[]}
post不要でしたので削除対応しました

2025-01-03 06:52 UTC, Yuya757 commented
react-material-ui-carouselを導入しました．前後の投稿も見れた方が良いですが，まだ使い方がつかめていません．また次へ送るボタンがカルーセルタグの中に入っているため，左右の端に配置することが難しそうです．現在のデザインでも見やすさ・わかりやすさは反映できそうですが，もう少し工夫できないか調べます．
![image](https://github.com/user-attachments/assets/7129a90a-9409-4022-9e75-8c78ecff1d55)

2025-02-13 09:02 UTC, Yuya757 commented
@azufb 結局，ダミーデータは読み込めていないのですが，エラー解消してメイン画面の表示はできるようになっております！ご確認お願いできます．
![image](https://github.com/user-attachments/assets/1874a650-9386-49f2-a857-ebf2aa89864d)

2025-02-15 03:24 UTC, azufb requested changes
@Yuya757 
1点だけ質問コメントしてます！！
ご確認のほど、よろしくお願いいたします！！

2025-02-15 03:24 UTC, azufb commented on src/routing/index.tsx
> +              <NovelViewPresentation
@Yuya757 
こちらって、Container側をelementにしたら表示できなかった感じですかね？？
`NovelViewContainer`で`NovelViewPresentation`呼び出しているので、`Container`を`element`にする方が良いかなと思ってます！

【補足】
一応、ページは他のページと同様に`pages`配下にPageコンポーネントを作って、それを`element`にするのがこのPJ的には合っているかなと思いますが、今回のPR上では対応不要です！
別のチケット（サブタスクかな？）を切って頂き、別のPRとして出して頂けると助かります！！

2025-02-15 14:34 UTC, Yuya757 commented on src/routing/index.tsx
> +              <NovelViewPresentation
@azufb いいえ，違和感はありつつも，コードエディタに言われるがままでした．Containerをelementにできましたのでプッシュします！
ページの件も了解しました，後日整理いたします！

2025-02-16 03:00 UTC, azufb approved these changes

2025-02-16 03:02 UTC, azufb commented
@Yuya757 
長らくご対応ありがとうございます！！
こちらのPRはひとまずマージとさせて頂きます！

2025-02-16 03:03 UTC, merged