後続・パラレル投稿取得APIの詳細定義・作り込み（CNV-117）
Conovel/frontend pull request #26
Opened 2024-11-30 11:32 UTC by ryo-i

## JIRAチケットURL

https://techno-kuro-novel.atlassian.net/browse/CNV-117

※CNV-117からCNV-96に向けたPRになります

---
## 実装内容

- developと同期
  - 以前作りかけていたCNV-117のフロント側の修正はdevelopとの差分が開いたため修正しづらくなった
  - そのため、一旦ブランチの内容を最新のdevelopと同じ内容に修正（CNV-96、CNV-117ブランチ共に）
  - その後にCNV-117にフロント側のAPIモックと動作確認用のボタンを追加
- 動作確認ボタン
  - 動作確認用ボタンは以前はApp.tsxに配置していたが、今はこのファイルはルーティング設定ファイルになっている
  - 今kanepionさんが修正している投稿閲覧画面に影響がないよう、トップ画面（NovelList）に動作確認用ボタンを配置
  - APIの動作確認に係る箇所には「API動作確認用」〜「API動作確認用 ここまで」というコメントをつけています
- jestテスト
  - テストファイル自体はSampleという名前にして見本に留める（緊急性は低いと判断） 
 
### 機能要件

このセクションでは、以下URL参照先（機能要件）の記載を引用し、どの要件を満たすための実装をしたのかを記載します。
https://techno-kuro-novel.atlassian.net/wiki/spaces/Conovel/pages/3145744
なお、上記URLに含まれない実装をしている場合は、適宜参照先URLを付して、記載を引用して記載してください。
必ず製造タスクの根拠を示してください。

　例　テーブル定義Miroやその他資料

- 機能要件1
- 機能要件2
- 機能要件3

また、上記要件資料を参照し、漏れがないことを確認したら、チェックします。

[] 要件漏れがないことを確認済み
[] 一部懸念あり

### 非機能要件

このセクションでは、以下URL参照先（非機能要件）の記載を引用し、どの要件を満たすための実装をしたのかを記載します。
https://techno-kuro-novel.atlassian.net/wiki/spaces/Conovel/pages/1376286/_PJ
なお、上記URLに含まれない実装をしている場合は、適宜参照先URLを付して、記載を引用して記載してください。

- 非機能要件1
- 非機能要件2
- 非機能要件3

以下非機能要件を遵守すべき事項を確認しチェック
[] CORS制約
[] XSS防止
[] CSRF防止
[] 認証中トークン
[] 広告枠

---

## 自身で確認した動作のエビデンス（スクショ等）

### 動作確認エビデンス1
例　未読通知を複数ページに渡って閲覧して、既読になる様子

API動作確認ボタン
![スクリーンショット 2024-11-30 20 09 45](https://github.com/user-attachments/assets/6110c1ff-3e08-4cde-b9f0-23e3d9534455)

ボタンを押した後（「吾輩は猫である」が表示される）
![スクリーンショット 2024-11-30 20 09 52](https://github.com/user-attachments/assets/799ce4cb-8f30-4c54-bfe9-e8fa4095d273)

リクエスト（`http://localhost:3001/v1/sentences/1`にGET→結果：200 OK）
![スクリーンショット 2024-11-30 20 11 47](https://github.com/user-attachments/assets/ceb51dc1-1b89-43b1-9059-5761b5557277)

レスポンス（データがSentencesの最新状態になっている）
![スクリーンショット 2024-11-30 20 11 57](https://github.com/user-attachments/assets/6192a333-08af-42f1-8acd-a2157d8213a2)

### 動作確認エビデンス2

---

## 結合テスト・受入テストに持ち越すテスト項目（必ず1つ以上作成）
本PullReqで洗い出し記載して、Mergeしたら、以下に整理転記する
https://techno-kuro-novel.atlassian.net/wiki/spaces/Conovel/pages/38567991

### テスト要求1

### テスト要求2

### テスト要求3

2024-11-30 12:12 UTC, ryo-i reviewed
beseブランチを変更

2024-11-30 12:29 UTC, azufb requested changes
@ryo-i 
1点修正提案コメントしております！
ご確認のほど、よろしくお願いいたします🙇‍♀

2024-11-30 12:29 UTC, azufb commented on src/features/NovelList/index.tsx
> +  // apiKey: 'your-api-key',
@ryo-i @technokuro 
APIエンドポイントのパスはenvに記載しておいてほしいかもです！
あと、axiosであれば、basePathの指定ができか気がするので、それで対応できると良いかもです。
API通信が入るコンポーネントごとに毎回localhostの指定があると大変だなぁと思いまして…💦
そのあたりもサンプル実装として対応頂けると助かります🙇‍♀

2024-11-30 12:29 UTC, azufb commented on src/features/NovelList/index.tsx
> +      console.error('Error fetching sentences:', error);
@ryo-i @technokuro 
今回のレビュー対応としては不要なのですが、エラー時の対応について決めておく必要ごあるかもですね。
エラーがわかるような画面にするかなど。

2024-12-01 09:08 UTC, ryo-i commented on src/features/NovelList/index.tsx
> +  // apiKey: 'your-api-key',
@azufb cc @technokuro @Yuya757 
ご確認ありがとうございます！修正しました
https://github.com/Conovel/frontend/pull/26/commits/0fa304e50a979f5ca0b2978bde1b889eccd7683f

envormentの`docker-compose.yml`にも.envファイルを参照する設定が必要でした。修正コミットをプッシュしましたので最新のenviromentからプルをお願いしますmm
https://github.com/Conovel/environment/commit/a99909b35a85d5552218540b1a7b35cc6957a8bb

また、envorment直下の.envファイルに新たな環境変数`VITE_DEVELOPMENT_API_BASE_URL`と`VITE_PRODUCTION_API_BASE_URL`を追加しました。下記からダウンロードお願いしますmm
- Googleドライブ＞Conovel-PJ情報＞環境変数＞`.env`

2024-12-01 09:09 UTC, ryo-i commented on src/features/NovelList/index.tsx
> +      console.error('Error fetching sentences:', error);
@azufb 
忘れないように`TODO`コメントを追加しました！
https://github.com/Conovel/frontend/commit/0fa304e50a979f5ca0b2978bde1b889eccd7683f

2024-12-01 09:10 UTC, ryo-i reviewed
@azufb cc @technokuro @Yuya757 
ご確認ありがとうございます！修正しましたmm

enviromentの`docker-compose.yml`や`.env`にも修正があり、コメントしましたので併せてご確認お願いしますmm

2024-12-02 11:28 UTC, azufb commented on src/features/NovelList/index.tsx
> +  // apiKey: 'your-api-key',
@ryo-i 
修正ありがとうございます！！
他のAPIのエンドポイントって、`v1`のあとに続く感じでしょうか？？
例えば、アカウント情報とかだと、`http://localhost:3001/v1/account`みたいな感じになるとか...

2024-12-02 22:26 UTC, ryo-i commented on src/features/NovelList/index.tsx
> +  // apiKey: 'your-api-key',
@azufb cc @technokuro 
はい、`/v1`までは全て統一で行こうかと思います。
今後、APIの内容がバージョンが変わるくらいの変更になる時に、`v1`と`v2`をしばらく並行させるなどの処置をすることが多いかなと思いまして。

2024-12-02 23:23 UTC, azufb commented on src/features/NovelList/index.tsx
> +  // apiKey: 'your-api-key',
@ryo-i 
承知いたしました！
ありがとうございます！！

2024-12-02 23:24 UTC, azufb approved these changes

2024-12-05 12:36 UTC, technokuro approved these changes

2024-12-05 12:36 UTC, merged