Origin/feature/cnv 76 novel view
Conovel/frontend pull request #38
Opened 2024-12-29 03:50 UTC by Yuya757

## JIRAチケットURL

---
## 実装内容

### 機能要件

このセクションでは、以下URL参照先（機能要件）の記載を引用し、どの要件を満たすための実装をしたのかを記載します。
https://techno-kuro-novel.atlassian.net/wiki/spaces/Conovel/pages/3145744
なお、上記URLに含まれない実装をしている場合は、適宜参照先URLを付して、記載を引用して記載してください。
必ず製造タスクの根拠を示してください。

　例　テーブル定義Miroやその他資料

- 機能要件1
- 機能要件2
- 機能要件3

また、上記要件資料を参照し、漏れがないことを確認したら、チェックします。

[] 要件漏れがないことを確認済み
[] 一部懸念あり

### 非機能要件

このセクションでは、以下URL参照先（非機能要件）の記載を引用し、どの要件を満たすための実装をしたのかを記載します。
https://techno-kuro-novel.atlassian.net/wiki/spaces/Conovel/pages/1376286/_PJ
なお、上記URLに含まれない実装をしている場合は、適宜参照先URLを付して、記載を引用して記載してください。

- 非機能要件1
- 非機能要件2
- 非機能要件3

以下非機能要件を遵守すべき事項を確認しチェック
[] CORS制約
[] XSS防止
[] CSRF防止
[] 認証中トークン
[] 広告枠

---

## 自身で確認した動作のエビデンス（スクショ等）

### 動作確認エビデンス1
例　未読通知を複数ページに渡って閲覧して、既読になる様子

### 動作確認エビデンス2

---

## 結合テスト・受入テストに持ち越すテスト項目（必ず1つ以上作成）
本PullReqで洗い出し記載して、Mergeしたら、以下に整理転記する
https://techno-kuro-novel.atlassian.net/wiki/spaces/Conovel/pages/38567991

### テスト要求1

### テスト要求2

### テスト要求3

2025-01-03 14:05 UTC, azufb requested changes
@Yuya757 
いくつかコメントしました！
ご確認お願いいたします！

2025-01-03 14:05 UTC, azufb commented on src/rooting/index.tsx
@Yuya757 
ルーティングの定義が2つ存在してそうなので、`src/rooting`のディレクトリは削除して頂いてOKかなと思います！！

2025-01-03 14:05 UTC, azufb commented on src/features/NovelInfo/index.tsx
> +                  chips={novel.chips}
@Yuya757 
`NovelProps`が定義されているのであれば`novel`と`novel.tags`など別々で渡すより、`NovelCardContainer`には`novel`だけ渡して、`NovelCardContainer`の中で`tags`とか`chips`とか展開できるのかな？と思ったのですが、どうでしょうか？

2025-01-04 05:22 UTC, Yuya757 commented on src/rooting/index.tsx
@azufb 気づいていませんでした...削除対応しました

2025-01-04 05:23 UTC, Yuya757 commented on src/features/NovelInfo/index.tsx
> +                  chips={novel.chips}
@azufb ありがとうございます．なるほどその通りですね．

2025-01-04 10:02 UTC, azufb requested changes
@Yuya757 
1点気になったのでコメントしてます！！

2025-01-04 10:02 UTC, azufb commented on src/rooting/index.tsx
@Yuya757 
細かいですが、`rooting`ではなく`routing`の方がスペル合っているような？？

あと、`routing`ディレクトリの方を消して頂いたようなのですが、そっち消しちゃうと`/terms`アクセスしても利用規約画面見れなくなっちゃいます...！！

2025-01-07 12:21 UTC, Yuya757 commented on src/rooting/index.tsx
見落としておりました...修正いたしました！

2025-01-09 12:28 UTC, azufb approved these changes

2025-01-09 12:29 UTC, merged